### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Ako-r** [KHU-AGI/BUS#1]
Hi! It is an interesting work! 
When will you release your code?

**Comment by rongtongxueya** [comment]
!Keeping an eye on this

**Comment by Ako-r** [comment]
Is it possible for you to share the trained model and a demo script for inference?

**Comment by hiyyg** [comment]
Estimated release time?

**Comment by dragoon0905** [comment]
Thank you for your interest in my work! I have now uploaded the code, the trained model, and script. If you have any questions while running the code, please feel free to ask.
